# yaml 配置
version: "3.7"
services:
  mysql:
    image: "bingozhou/mysql5.7:latest"
    ports:
      - "33061:668"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "bluebell"
      MYSQL_PASSWORD: "123456"
    volumes:
      - ./init.sql:/data/application/init.sql
  redis:
    image: "redis:latest"
    ports:
      - "33061:669"
  bubble_app:
    build: .
    command: sh -c "./wait-for.sh mysql:668 redis:669 -- ./bluebell ./config.json"
    depends_on:
      - mysql
      - redis
    ports:
      - "8888:8888"